### ISSUE TITLE
ASM viewer does not work

### ISSUE THREAD

**Issue by gfernval** [sjgray/cbm-transfer#6]
In selecting a example.asm ASCII file and going to viewer, all viewers work except ASM viewer, when selecting ASM vierwer gives the error: "Missing file d:\opencbm\" I have ACME 0.97 installed (acme.exe) in d:\opencbm. I use Windows XP SP3 installed in D: drive

**Comment by sjgray** [comment]
The ASM viewer works on binary files, not ASCII. Does "Missing file d:\opencbm" have anything after? There should be some filename there.

**Comment by gfernval** [comment]
Can you let me know a place where can I download a suitable binary file? I have tried with a C64 .prg file but does not work.

Also, in trying to compile with Visual Basic 6.0 SP5 gives the errors (when loading cbmxfer.vbp):

frmmain.log: line 669: Class MSComDlg.CommonDialog of control CommonDialog1 was not a loaded control class
frmviewer.log: line 1566: Class MSComDlg.CommonDialog of control CommonDialog was not a loaded control class

and when trying to compile (Start with Full Compile):

"Compile error: User-defined type not defined"

in frmMain (Code) line Private Function DoCommand(Action as String...)

What I´m missing?

**Comment by gfernval** [comment]
Does "Missing file d:\opencbm" have anything after?

no, only shows the error: "Missing file:D:\opencbm\"

**Comment by gfernval** [comment]
no, only shows exactly the error: "Missing file:D:\opencbm\" when trying ASM viewer in a .prg file

**Comment by sjgray** [comment]
It's been a while, but it sounds like the commondialog control was not installed or is not registered properly. Try re-installing VisualBASIC. This is the control used to do the OPEN/SAVE dialog window.

The ASM viewer expects a binary file, which could be a PRG file but you can't tell without loading it. Most binary files from other systems will have a .BIN or .ROM extension. If you go on zimmers.net you can find many rom firmware files you can try with. The ASM viewer is a disassembler, which takes the binary and makes the source code for you. It has it's own readme file you can view if you expand the ASM view using the control near the top left. Once disassembled you can use ACME to re-assemble it. If you are looking to re-assemble an existing 6502 assembly file like .ASM then it's probably easier to just use the command prompt and call it directly. I like creating a MAKE.BAT file with all the parameters so it's easy to type.

I will look into the error message.

**Comment by gfernval** [comment]
Have tested cbmxfer 1.25 test and 1.24 and also fail in a computer with Windows 10 (64 bit) Same error. Does the ASM viewer expect any specific file extension for a file to disassemble? Does the ASM viewer needs acme.exe for disassembling?Update: version 1.0 of cbmxfer works well, all other versions (1.10, 1.19 test, 1.22a, 1.24, 1.25 test, 2.0 beta) fails

**Comment by gfernval** [comment]
Solved the two following errors in trying to compile cbmxfer:

frmmain.log: line 669: Class MSComDlg.CommonDialog of control CommonDialog1 was not a loaded control class
frmviewer.log: line 1566: Class MSComDlg.CommonDialog of control CommonDialog was not a loaded control class

But as soon as I run "Run -> Start With Full Compile" shows the error:

"Compile error: User-defined type not defined" in the following line:

Private Function DoCommand(Action As String, Args As String, WaitMessage A String, Optional DeleteOutFile As Boolean = True) As ReturnStringType

is the line 4486 of file frmMain.frm

**Comment by gfernval** [comment]
In my Visual Studio 6, if you go to Project -> References I have activated:

Visual Basic for Applications
Visual Basic runtime objects and procedures
Visual Basic objects and procedures

**Comment by sjgray** [comment]
There is no special extension for binaries. It will take any PRG, SEQ, ROM, or BIN file automatically. Other extensions will ask what you want it to do. There is a special extension for the project file ".ASM-PROJ" that will be recognized if you load a file with the same name, like "rom.bin" would automatically load "rom.asm-proj" in order to bring in your symbols and settings etc.
I just tried the version 1.25 exe and I have no problem or errors loading any file. It also compiles fine from source, but it's never been an issue for me. I currently have a windows 10 development computer, but I've used everything from XP and up over the years as I've upgraded my PCs. For the "references" menu I also have "OLE Automation" and "Microsoft Data Formatting.." selected. If you go to Project, "CBMxfer Properties" make sure you have "Project Type: Standard EXE" and "Startup Object: frmMain". I'm not sure what else it might be.

**Comment by gfernval** [comment]
Forget all that I´m told you, found the problem: I have downloaded the github .zip file from https://github.com/sjgray/cbm-transfer/archive/refs/heads/master.zip link, but the problem is that is such file the .txt files, .frm files, .dat files, all text files end with LF character, not CR/LF pair characters! I have used an utility to change LF ending to CR/LF ending files and all the programs works fine, including the compilation. The source files are from 1.24 version, I´m interested in the 1.25 version, can you send me the source files of 1.25 version? (gfernval@hotmail.com)

**Comment by sjgray** [comment]
Appologies, I do not have 1.25 source. I did not have a chance to officially release it.  What I had was 1.5 source which ultimately became 2.00BETA. I know it's been a while, but I will eventually release an official 2.0 with source when it's ready.

I'm glad you figured out the issue.
